import { StyleSheet } from "react-native";

const colors = {
  primary: "#8EFF00",
  inputBg: "#FFFFFF",
  inputBorder: "#F2F2F2",
  inputBorderFocus: "#8EFF00",
  text: "#000000",
  textSecondary: "#6B7280",
  error: "#EF4444",
  disabled: "#D1D5DB",
};

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#222",
    padding: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 16,
    marginTop: 28,
  },
  logo: {
    width: 40,
    height: 40,
    marginBottom: 10,
  },
  title: {
    fontSize: 22,
    fontWeight: "900",
    color: "#fff",
    textAlign: "center",
    fontFamily: "Montserrat",
    marginBottom: 10,
  },
  inputSection: {
    width: "90%",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#2C2C2C",
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 14,
    fontSize: 15,
    color: "#fff",
    marginBottom: 10,
    fontFamily: "Montserrat",
  },
  forgotPassword: {
    color: "#fff",
    textDecorationLine: "underline",
    fontSize: 13,
    marginBottom: 6,
    fontFamily: "Montserrat",
  },
  errorText: {
    color: "#FF6B6B",
    fontSize: 13,
    marginBottom: 6,
    textAlign: "center",
    fontFamily: "Montserrat",
  },
  button: {
    backgroundColor: "#A1F763",
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
    width: "90%",
    marginTop: 12,
  },
  buttonText: {
    color: "#222",
    fontWeight: "bold",
    fontSize: 16,
    fontFamily: "Montserrat",
  },
  divider: {
    width: "90%",
    height: 1,
    backgroundColor: "#444",
    marginVertical: 20,
  },
  socialSection: {
    width: "90%",
    marginBottom: 12,
  },
  socialButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  socialIcon: {
    width: 18,
    height: 18,
    marginRight: 8,
  },
  socialButtonText: {
    color: "#222",
    fontWeight: "bold",
    fontSize: 15,
    fontFamily: "Montserrat",
  },
  inviteSection: {
    width: "90%",
    marginTop: 30,
    marginBottom: 12,
    alignItems: "center",
  },
  inviteLabel: {
    color: "#fff",
    fontSize: 14,
    marginBottom: 6,
    fontFamily: "Montserrat",
  },
  inviteInput: {
    backgroundColor: "#2C2C2C",
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 14,
    fontSize: 15,
    color: "#fff",
    width: "100%",
    fontFamily: "Montserrat",
  },
  termsText: {
    color: "#fff",
    fontSize: 12,
    textAlign: "center",
    marginBottom: 14,
    fontFamily: "Montserrat",
  },
  link: {
    color: "#A1F763",
    textDecorationLine: "underline",
    fontWeight: "bold",
    fontFamily: "Montserrat",
  },
});
